# Lab - File Handling & Numpy Arrays

Complete the tasks listed below. You can submit the completed lab until 11:59 PM in the night.

### Task 1 (3 marks)

The __data__ folder contains five csv files with column names `Col_A`, `Col_B`, `Col_C`, `Col_D`, and `Col_E`, as well as some fictitious data. 

Write Python code that extracts all the lines from each file (except the first line which contains the column names) and creates a list of those integers for each file. For example, the list of integers for the file `Y2015-data.csv` would be [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20].

Then write code that extracts the year (such as `Y2015`) from each file path (such as `data\\Y2015-data.csv`) and creates a key with that year in a dictionary named __data_dict__. The value for the key (e.g. `Y2015`) should be the list of integers extracted from that file (i.e. `Y2015-data.csv`). You can write all of the above mentioned code in a single cell.

Some starter code is reproduced below for your convenience. Also, the desired output __data_dict__ is shown below.

<img src="figs/data_dict.png" width="1000" align="left">

In [1]:
import glob

In [2]:
path = 'data' # use your path
allFiles = []
allFiles = glob.glob(path + "/*.csv")

In [66]:
allFiles.sort()
allFiles

['data/Y2015-data.csv',
 'data/Y2016-data.csv',
 'data/Y2017-data.csv',
 'data/Y2018-data.csv',
 'data/Y2019-data.csv']

In [143]:
import re
data_dict = dict()
for file in allFiles:
    match = re.search('Y[0-9]{4}',file)
    
    # if file doesn't match, skip it
    if match == None:
        continue  
    
    year = match.group(0)
    with open(file) as fhandle:
        next(fhandle)
        ls = list()
        for line in fhandle:
            line = line.strip()
            for num in line.split(','):    
                ls.append(int(num))      
    data_dict[year] = ls
print(data_dict)

{'Y2015': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'Y2016': [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40], 'Y2017': [41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60], 'Y2018': [61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80], 'Y2019': [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]}


### Task 2 (0.5 mark)

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10 (inclusive of both ends).

In [76]:
### Write your code below this comment.
import numpy as np
mat1 = np.random.randint(low=2, high=11, size=(3,3))
print("Random matrix of shape (3,3): \n",mat1)

Random matrix of shape (3,3): 
 [[6 9 3]
 [4 3 4]
 [7 3 3]]


### Task 3 (0.5 mark)

Write a NumPy program to convert the array __[1, 2, 3, 4, 5]__ to float type. Print both the original as well as the converted array.

__This task requires a little bit of creativity. Free free to Google around to find the required function / method.__

In [84]:
### Write your code below this comment.
array1 = np.array([1, 2, 3, 4, 5])
conv_array = array1.astype(float)
print("Original array:", array1)
print("Converted array:", conv_array)

Original array: [1 2 3 4 5]
Converted array: [1. 2. 3. 4. 5.]


### Task 4 (2 marks)

Write a NumPy program to create a 5x5 matrix with all 1's. Then write code to modify the matrix such that it has 1 on the borders and 0 inside. Print both the original as well as the modified matrix. A screenshot of the original as well as the modified matrix is shown below:

<img src="figs/task4.png" width="320" align="left">

In [106]:
### Write your code below this comment.
original_array = np.ones((5,5))
print("Original array: \n",original_array)
ones_zeros_array = original_array
ones_zeros_array[1:4,1:4] = 0
print("1 on the borders and 0 inside the array \n",ones_zeros_array)

Original array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the borders and 0 inside the array 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Task 5 (1 mark)

Write a NumPy program to get the unique elements from the following arrays: 
- __[10, 10, 20, 20, 30, 30]__
- __[[1, 1], [2, 3]]__

Print both the original arrays as well as the arrays with unique elements. The following is a pictorial representation of this operation:

<img src="figs/array_unique.png" width="350" height="350" align="left">

__This task requires a little bit of creativity. Free free to Google around to find the required function / method.__

In [116]:
### Write your code below this comment.
array1 = np.array([10, 10, 20, 20, 30, 30])
array2 = np.array([[1,1],[2,3]])
print("Original array 1: \n", array1)
print("Unique elements from original array 1: \n", np.unique(array1))
print("Original array 2: \n", array2)
print("Unique elements from original array 2: \n", np.unique(array2))

Original array 1: 
 [10 10 20 20 30 30]
Unique elements from original array 1: 
 [10 20 30]
Original array 2: 
 [[1 1]
 [2 3]]
Unique elements from original array 2: 
 [1 2 3]


### Task 6 (1.5 marks)

Write a NumPy program to change the dimensions of the 1D array __[1, 2, 3, 4, 5, 6, 7, 8, 9]__ to a 3x3 matrix. Explain why the shape of the 1D array displays 9 rows and no columns although it has just a single row/column. How could this possibly be corrected?

In [144]:
### Write your code below this comment.
array1 = np.array([1,2,3,4,5,6,7,8,9])
print(array1.shape)
mat1 = array1.reshape(3,3)
print(mat1)
print(mat1.shape)

(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


__Ans:__ The shape atribute of an array is represented as a tuple of (rows,columns) which only applies for 2 dimensional arrays. A 1D array only has 1 dimension so its shape can't be represented as (rows,columns) but since the attribute is represented as a tuple it has to include the comma, so the result is shown as (number of elements,). The 9 is the number of elements in the array.

In [10]:
### Write your code below this comment.

### Task 7 (1.5 marks)

Create the matrices shown below:

<img src="figs/task7-1.png" width="230" align="left">

Then combine them into a single matrix named __result__ that looks as follows:

<img src="figs/task7-2.png" width="185" align="left">

Once you have created the __result__ matrix, find the total number of its elements that are greater than or equal to __34__.

In [133]:
### Write your code below this comment.
mat1 = np.array([73,10,21,81]).reshape(2,2)
mat2 = np.array([70,80,48,65]).reshape(2,2)
mat3 = np.array([83,89,50,30]).reshape(2,2)
mat4 = np.array([20,20,15,40]).reshape(2,2)
mat5 = np.array([33,66,10,58]).reshape(2,2)
mat6 = np.array([33,32,75,24]).reshape(2,2)

arr1 = np.hstack((mat1,mat2,mat3))
arr2 = np.hstack((mat4,mat5,mat6))
result = np.vstack((arr1,arr2))
print(result)

print ("Elements greater than or equal to 34:", len(result[result>=34]))


[[73 10 70 80 83 89]
 [21 81 48 65 50 30]
 [20 20 33 66 33 32]
 [15 40 10 58 75 24]]
Elements greater than or equal to 34: 13


### Task 8 (Bonus: 1 mark)

Create the arrays __a1__ and __a2__ as shown below:

<img src="figs/task8.png" width="300" align="left">

Then, as revealed in class, calculate their dot as well as cross product. Print both the original arrays as well as the resulting dot and cross product arrays.

__This task requires a little bit of creativity. Free free to Google around to find the required function.__

<u>Note:</u> The Bonus mark would only be added if the score you obtained in the lab assignment is less than the maximum score. For example, if you get 9.5/10 plus 1 bonus mark, your score will be elevated to 10 and not 10.5. If you already got the maximum score, the bonus mark will be ignored.

In [139]:
### Write your code below this comment.
a1 = np.array([2,3,4,5,6,7,8,9,10]).reshape((3,3))
print("a1 \n", a1)
a2 = np.array([4,5,6,7,8,9,10,11,12]).reshape((3,3))
print("a2 \n", a2)

dot_product = np.dot(a1,a2)
print("\n Dot product \n", dot_product)
cross_product = np.cross(a1,a2)
print("\n Cross product \n", cross_product)

a1 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
a2 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 Dot product 
 [[ 69  78  87]
 [132 150 168]
 [195 222 249]]

 Cross product 
 [[-2  4 -2]
 [-2  4 -2]
 [-2  4 -2]]
